import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { DoadorProvider } from "@/app/contexts/DoadorContext";
import { BeneficiarioProvider } from "@/app/contexts/BeneficiarioContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Envolvemos toda a aplicação com os dois Providers */}
        <DoadorProvider>
          <BeneficiarioProvider>
            {children}
          </BeneficiarioProvider>
        </DoadorProvider>
      </body>
    </html>
  );
} 